if not game:IsLoaded() then repeat game.Loaded:Wait() until game:IsLoaded() end
getgenv().Script_Mode = "Kaitun_Script"
_G.Settings = {
    PlantSettings = {
        Limit = 800,
        Plant = {
			["Venus Fly Trap"] = 1,
			["Candy Sunflower"] = 1,
			["Burning Bud"] = 1,
			["Lumira"] = 1,
			["Crocus"] = 1,
			["Giant Pinecone"] = 1,
			["Traveler's Fruit"] = 1,
			["Moonflower"] = 1,
			["Blood Banana"] = 1,
			["Dandelion"] = 1,
			["Cocovine"] = 1,
			["White Mulberry"] = 1,
			["Cactus"] = 1,
			["Lemon"] = 1,
			["Cacao"] = 1,
			["Watermelon"] = 1,
			["Aloe Vera"] = 1,
			["Stonebite"] = 1,
			["Grape"] = 1,
			["Dragon Pepper"] = 1,
			["Easter Egg"] = 1,
			["Nectarshade"] = 1,
			["Cranberry"] = 1,
			["Cauliflower"] = 1,
			["Glowshroom"] = 1,
			["Moonglow"] = 1,
			["Violet Corn"] = 1,
			["Celestiberry"] = 1,
			["Foxglove"] = 1,
			["Succulent"] = 1,
			["Purple Dahlia"] = 1,
			["Ember Lily"] = 1,
			["Paradise Petal"] = 1,
			["Firefly Fern"] = 1,
			["Beanstalk"] = 1,
			["Papaya"] = 1,
			["Delphinium"] = 1,
			["Ice Cream Bean"] = 1,
			["Cherry Blossom"] = 1,
			["Lime"] = 1,
			["Prickly Pear"] = 1,
			["Grand Volcania"] = 1,
			["Bee Balm"] = 1,
			["Cursed Fruit"] = 1,
			["Lily of the Valley"] = 1,
			["Feijoa"] = 1,
			["Strawberry"] = 1,
			["Peach"] = 1,
			["Lotus"] = 1,
			["Raspberry"] = 1,
			["Peace Lily"] = 1,
			["Guanabana"] = 1,
			["Mushroom"] = 1,
			["Hive Fruit"] = 1,
			["Parasol Flower"] = 1,
			["Orange Tulip"] = 1,
			["Eggplant"] = 1,
			["Dragon Fruit"] = 1,
			["Pink Lily"] = 1,
			["Liberty Lily"] = 1,
			["Noble Flower"] = 1,
			["Durian"] = 1,
			["Moon Mango"] = 1,
			["Chocolate Carrot"] = 1,
			["Bone Blossom"] = 1,
			["Horsetail"] = 1,
			["Carrot"] = 1,
			["Pitcher Plant"] = 1,
			["Rafflesia"] = 1,
			["Green Apple"] = 1,
			["Merica Mushroom"] = 1,
			["Bamboo"] = 1,
			["Red Lollipop"] = 1,
			["Pineapple"] = 1,
			["Moon Blossom"] = 1,
			["Kiwi"] = 1,
			["Crimson Vine"] = 1,
			["Mango"] = 1,
			["Candy Blossom"] = 1,
			["Lingonberry"] = 1,
			["Sugar Apple"] = 1,
			["Blueberry"] = 1,
			["Apple"] = 1,
			["Loquat"] = 1,
			["Lilac"] = 1,
			["Passionfruit"] = 1,
			["Sunflower"] = 1,
			["Rose"] = 1,
			["Nectarine"] = 1,
			["Starfruit"] = 1,
			["Corn"] = 1,
			["Boneboo"] = 1,
			["Wild Carrot"] = 1,
			["Pepper"] = 1,
			["Tomato"] = 1,
			["Bell Pepper"] = 1,
			["Nightshade"] = 1,
			["Suncoil"] = 1,
			["Pumpkin"] = 1,
			["Taro Flower"] = 1,
			["Mint"] = 1,
			["Fossilight"] = 1,
			["Moon Melon"] = 1,
			["Daffodil"] = 1,
			["Horned Dinoshroom"] = 1,
			["Honeysuckle"] = 1,
			["Banana"] = 1,
			["Pear"] = 1,
			["Lavender"] = 1,
			["Bendboo"] = 1,
			["Rosy Delight"] = 1,
			["Avocado"] = 1,
			["Soul Fruit"] = 1,
			["Coconut"] = 1,
			["Elephant Ears"] = 1,
			["Cantaloupe"] = 1,
			["Firework Flower"] = 1,
			["Nectar Thorn"] = 1,
			["Amber Spine"] = 1		
		},
        Destroy = {
            WhenMoney = 50000,
            Plant = {
                "Strawberry"
            }
        }
    },
    SeedsSetting = {
        "Rafflesia",
		"Green Apple",
		"Avocado",
		"Banana",
        "Pineapple",
		"Kiwi",
		"Bell Pepper",
		"Prickly Pear",
		"Loquat",
		"Feijoa",
		"Watermelon",
		"Cauliflower",		
        "Burning Bud",
        "Corn",
        "Sugar Apple",
        "Daffodil",
        "Tomato",
        "Carrot",
        "Beanstalk",
        "Pumpkin",
        "Bamboo",
        "Strawberry",
        "Cactus",
        "Dragon Fruit",
        "Orange Tulip",
        "Pepper",
        "Cacao",
        "Mushroom",
        "Coconut",
        "Blueberry",
        "Apple",
        "Mango",
        "Grape",
        "Ember Lily",
        "Giant Pinecone"
    },
    EggSettings = {
        StartBuyEggWhen = 150000,
        SelectEggs = {
            "Mythical Egg",
            "Bug Egg",
            "Paradise Egg",
            "Rare Egg",
            "Bee Egg",
			"Legendary Egg",
			"Dinosaur Egg",
			"Night Egg",
			"Primal Egg",
			"Fake Egg",
			"Rare Summer Egg",
			"Oasis Egg",
			"Premium Anti Bee Egg",
			"Common Summer Egg",
			"Common Egg",
			"Anti Bee Egg"
        },
    },
    Webhook = "",
    UpgradeEggSlots = 2,
    UpgradePetSlots = 2,
    PetSettings = {
        Sell = {
            "Dog",
        },
        UpgradeSlots = {
            "Chicken", "Rooster"
        },
        Equip = {
            "Chicken", "Rooster"
        },
        Lock = {
            Weight = 10,
            Enabled = true
        }
    },
    CraftSettings = {
        Enabled = true,
        Workbench = "Anti Bee Egg",
        SeedEventWorkbench = "",
        DinoEventWorkbench = ""
    },
    PrehistoricEvents = {
        ClaimReward = true,
        PetToTrade = {
            "Dog"
        },
        DinoSourUpgrade = {
            ['Enabled'] = true
        }
    },
    GearStocksBuy = {
        ""
    },
    UseSeedPack = true,
    CropSettings = {
        ['DelayTime'] = 10,
        ['TimeCrop'] = 10
    }
}
getgenv().Key = "MARU-8LY9G-0MSC9-CKM9-BB2VD-Z51P"
getgenv().id = "1027130540664565830"
loadstring(game:HttpGet("https://raw.githubusercontent.com/xshiba/MaruBitkub/main/Mobile.lua"))()
